services:
  postgres:
    image: postgres:17-alpine
    container_name: gear-book-postgres

    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USED: gearbook
      POSTGRES_PASSWORD: gearbook

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
