CREATE TABLE inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku varchar(120) UNIQUE NOT NULL ,
    name varchar(48) NOT NULL,
    description varchar(256),
    total_quantity int
        CHECK ( total_quantity >= 0 ) NOT NULL ,
    available_quantity int
        CHECK ( available_quantity >= 0 AND available_quantity <= total_quantity ) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    active BOOLEAN NOT NULL DEFAULT TRUE
);