CREATE TABLE reservation
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id uuid NOT NULL UNIQUE,
    inventory_id bigint NOT NULL,
    quantity int NOT NULL check ( quantity > 0 ),
    status varchar NOT NULL CHECK ( status IN ('RESERVED', 'RELEASED') ),
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_reservation_inventory FOREIGN KEY (inventory_id) REFERENCES inventory(id)

)