spring.application.name=inventory-service

spring.datasource.url=jdbc:postgresql://localhost:5433/inventory_db
spring.datasource.username=gearbook
spring.datasource.password=gearbook

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
